# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GameBoard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameBoard

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Google/SignIn'

  target 'GameBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GameBoard-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameBoard-tvOS

  target 'GameBoard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
