# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GameBoard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameBoard

  # RNFirebase Modules.
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'

  target 'GameBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GameBoard-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameBoard-tvOS

  target 'GameBoard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
