fastlane_version '2.72.0'

before_all do
  # ensure_git_branch
  # ensure_git_status_clean
  # git_pull
end

platform :ios do

    before_all do
      # Setup CircleCI (if needed!)
      setup_circle_ci
    end

    # Runs the tests.
    desc 'Run tests'
    lane :test do
      scan(project: "./ios/GameBoard.xcodeproj", scheme: "GameBoard")
    end

    # Setup certificates.
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      match(app_identifier: 'com.dwmkerr.gameboard', type: 'development', readonly: true)
      match(app_identifier: 'com.dwmkerr.gameboard', type: 'appstore', readonly: true)
    end

    # Build the app.
	desc 'Build the iOS application.'
	lane :build do
      register_devices(username: "dwmkerr@gmail.com", devices_file: "./fastlane/devices.txt")
      match(app_identifier: 'com.dwmkerr.gameboard', type: 'adhoc', force_for_new_devices: true)
	  increment_build_number(xcodeproj: './ios/GameBoard.xcodeproj')
      
	  gym(scheme: 'GameBoard', project: './ios/GameBoard.xcodeproj')
	end
end

platform :android do

  # Clones the dwmkerr repo to grab the android keystore.
  desc 'Download gameboard.keystore'
  lane :download_keystore do
    sh("rm -rf ./dwmkerr")
    sh("git clone --depth=1 -b fastlane-match git@github.com:dwmkerr/dwmkerr.git")
    sh("cp -f dwmkerr/keystores/gameboard.keystore ../android/app/gameboard.keystore")
    sh("rm -rf ./dwmkerr")
  end

  # Android Lanes
  desc 'Build the Android application.'
  lane :build do
    download_keystore
    gradle(
      task: 'clean',
      project_dir: 'android/',
      properties: {
        "GAMEBOARD_RELEASE_KEY_PASSWORD" => ENV["GAMEBOARD_RELEASE_KEY_PASSWORD"],
        "GAMEBOARD_RELEASE_STORE_PASSWORD" => ENV["GAMEBOARD_RELEASE_STORE_PASSWORD"]
      },
      print_command: false
    )
    gradle(
      task: 'assembleRelease',
      project_dir: 'android/',
      properties: {
        "GAMEBOARD_RELEASE_KEY_PASSWORD" => ENV["GAMEBOARD_RELEASE_STORE_PASSWORD"],
        "GAMEBOARD_RELEASE_STORE_PASSWORD" => ENV["GAMEBOARD_RELEASE_STORE_PASSWORD"]
      },
      print_command: false
    )

    # Move our apk into the artifacts.
    sh("mkdir -p ../artifacts/android")
    sh("cp ../android/app/build/outputs/apk/app-release.apk ../artifacts/android/GameBoard.apk")
  end
end


